// https://nuxt.com/docs/api/configuration/nuxt-config

import tailwindcss from '@tailwindcss/vite';

export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  css: ['~/assets/css/main.css'],
  devtools: { enabled: false },
  modules: [
    '@nuxt/test-utils',
    '@nuxt/image',
    '@nuxt/icon',
    '@nuxt/fonts',
    '@nuxt/eslint',
    '@nuxt/ui',
    'nuxt-gtag',
    '@nuxtjs/sitemap',
  ],
  // Google analytics
  gtag: {
    id: 'G-1YBT2BFVT9',
  },
  site: {
    name: 'racelist.gr',
    url: 'https://racelist.gr',
    trailingSlash: true,
  },
  vite: {
    plugins: [tailwindcss()],
  },
  nitro: {
    prerender: {
      crawlLinks: true,
      failOnError: false,
      routes: [
        '/',
        '/about/',
        '/cooper-test/',
        '/faq/',
        '/gel-calculator/',
        '/hydration-calculator/',
        '/pace-calculator/',
        '/tools-for-runners/',
        '/agwnes/',
        '/agwnes/kalentari-agwnwn-febrouarios-2025/',
        '/agwnes/kalentari-agwnwn-martios-2025/',
        '/agwnes/kalentari-agwnwn-aprilios-2025/',
        '/agwnes/kalentari-agwnwn-maios-2025/',
        '/agwnes/kalentari-agwnwn-iounios-2025/',
        '/agwnes/kalentari-agwnwn-ioulios-2025/',
        '/agwnes/kalentari-agwnwn-augoustos-2025/',
        '/agwnes/kalentari-agwnwn-septembrios-2025/',

        // arthra
        '/arthra/',
        '/arthra/3-tropoi-apotherapies-apo-hmimarathonio/',
        '/arthra/adidas-running-shoes/',
        '/arthra/energeiaka-gel-gia-treximo-podilasia/',
        '/arthra/garmin-fenix-8/',
        '/arthra/kardiakos-palmos-sto-treximo/',
        '/arthra/nike-running-shoes/',
        '/arthra/o-termatismos-enos-agwna/',
        '/arthra/ofeli-treximatos/',
        '/arthra/papoutsia-gia-treximo-dromou/',
        '/arthra/pws-na-vreis-xrono-gia-treximo/',
        '/arthra/smartwatches-gia-dromeis-kai-podilates/',
        '/arthra/suunto-peak-9-pro/',
        '/arthra/ta-pio-gnwsto-problimata-dromewn/',
        '/arthra/ti-fame-gia-prwino-prin-tin-proponisi/',
        '/arthra/ti-trwme-prin-enan-agwna-treximatos/',
        '/arthra/garmin-forerunner-955-kai-955-solar/',
        '/arthra/garmin-forerunner-965/',
        '/arthra/garmin-fenix-7x-solar/',
        '/arthra/suunto-run/',
        '/arthra/new-balance-rebel-v5/',
        '/arthra/garmin-forerunner-970/',
        '/arthra/zoni-garmin-hrm-600/',

        // agwnes
        '/agwnas/11o-evrotas-run/',
        '/agwnas/12os-dromos-seich-sou/',
        '/agwnas/12os-prasinos-imimarathonios/',
        '/agwnas/13os-chios-half-marathon-2025/',
        '/agwnas/13os-chortiatis-trail-run/',
        '/agwnas/13os-imimarathonios-aigialeias/',
        '/agwnas/13os-vatikiotikos-agonas-zois/',
        '/agwnas/14os-agonas-dromou-ioannis-kapodistrias/',
        '/agwnas/14os-ippokrateios-agonas-dromou/',
        '/agwnas/14os-taygetos-challenge/',
        '/agwnas/16os-imimarathonios-kalampaka-trikala-thanasis-stamopoulos/',
        '/agwnas/18os-marathonios-messinis/',
        '/agwnas/19os-marathonios-megas-alexandros/',
        '/agwnas/1o-sithonia-trail-run/',
        '/agwnas/1o-sohos-trail-run/',
        '/agwnas/1o-spetses-mountain-run/',
        '/agwnas/21os-dromos-thysias-iroikis-polis-naousas/',
        '/agwnas/23os-dromos-argolikou-kolpou-panagiotis-papavasileiou/',
        '/agwnas/25os-agonas-dromou-kalamatas/',
        '/agwnas/25os-authentikos-euchideios-athlos/',
        '/agwnas/25os-dromos-vounou-ymittos-2025/',
        '/agwnas/26os-agonas-dromou-sto-alsos-dafniou/',
        '/agwnas/27os-logicom-cyprus-marathon/',
        '/agwnas/2nd-panetoliko-mountain-trail-run/',
        '/agwnas/2o-andros-trail-challenge/',
        '/agwnas/2o-grevena-city-run/',
        '/agwnas/2os-pallinios-dromos/',
        '/agwnas/2os-paraktios-nychterinos-imimarathonios-thermaikou-antonis-matzaris/',
        '/agwnas/38os-korakovounios-dromos/',
        '/agwnas/3o-eyrytania-triantafilia-mountain-trail-race/',
        '/agwnas/3o-santa-run/',
        '/agwnas/3os-imimarathonios-patras/',
        '/agwnas/4o-cholomon-trail-2025/',
        '/agwnas/4o-ipsilantis-trail/',
        '/agwnas/4o-pamvotis-view-trail/',
        '/agwnas/4o-paros-way/',
        '/agwnas/4os-agonas-dromou-gaudou/',
        '/agwnas/4os-apostolos-silas-trail-adventure/',
        '/agwnas/4os-godzilla-xanthi-trail/',
        '/agwnas/4th-evrytania-trail-races-2025/',
        '/agwnas/5i-gyra-manis/',
        '/agwnas/5o-agrinio-city-trail/',
        '/agwnas/5oi-agones-vasiliki-lefkada-road-mountain-race/',
        '/agwnas/5os-agonas-dromou-falannaion/',
        '/agwnas/5os-nychterinos-agonas-thrakis/',
        '/agwnas/5th-chios-hardstone-trail-run/',
        '/agwnas/6o-agrinio-night-run-santa-run/',
        '/agwnas/6os-atlas-trail-running/',
        '/agwnas/6os-vyzantinos-agonas-dromou-50chlm-dimou-megareon/',
        '/agwnas/75o-benizeleio-dromo/',
        '/agwnas/7h-leivadouria-fysiolatriki-diadromi/',
        '/agwnas/7o-faneromeni-trail/',
        '/agwnas/7os-dromos-mathiton/',
        '/agwnas/8o-dekari-parkou/',
        '/agwnas/8o-gentiki-trail-21chlm-gentikaki-trail-5-1chlm/',
        '/agwnas/8os-agonas-dromou-mahis-faraggiou-kantanou/',
        '/agwnas/8os-agonas-pediou-areos/',
        '/agwnas/8os-imimarathonios-ioanninon/',
        '/agwnas/9o-no-finish-line/',
        '/agwnas/9os-agonas-agchaiou-orous/',
        '/agwnas/9os-agonas-dromou-mnimeion-thessalonikis/',
        '/agwnas/9os-dromos-tou-giofyriou/',
        '/agwnas/9os-imimarathonios-volou-30o-i-love-volos-run/',
        '/agwnas/9os-lailias-mountain-running/',
        '/agwnas/9os-oreinos-agonas-levados-mountain-trail-2025/',
        '/agwnas/agonas-dromou-limnis-marathona-2025/',
        '/agwnas/agones-gia-to-perivallon-2025-limni-marathona/',
        '/agwnas/agones-yperapostaseon-entos-stadiou-megara/',
        '/agwnas/chania-trail-run-2025/',
        '/agwnas/coast-to-coast-race-2025/',
        '/agwnas/cretan-backyard-ultra-2026/',
        '/agwnas/crete-marathon-2025/',
        '/agwnas/dromos-thysias-aggelis-govios/',
        '/agwnas/duth-campus-run-2025/',
        '/agwnas/epidavrios-dromos-2025-theater-2-theater/',
        '/agwnas/goulinas-trail-2025/',
        '/agwnas/ierapetra-city-run-vol-5/',
        '/agwnas/ierapetra-santa-run-vol-3/',
        '/agwnas/imimarathonios-agapis-mytilinis-2025/',
        '/agwnas/imimarathonios-athinas-2025/',
        '/agwnas/kanalaki-run-2025/',
        '/agwnas/karpathos-run-2025/',
        '/agwnas/kassios-dias-trail-race-2025/',
        '/agwnas/katerini-run-2025/',
        '/agwnas/kerkini-lake-run-2025/',
        '/agwnas/koziakas-trail/',
        '/agwnas/koziakas-trail-running-2025/',
        '/agwnas/lesvos-trail-2025/',
        '/agwnas/life-run/',
        '/agwnas/lycabettus-run-2025/',
        '/agwnas/mamali-trail-run-2025/',
        '/agwnas/marathon-lake-run-2025/',
        '/agwnas/marathonios-nafpliou-2025/',
        '/agwnas/mazi-sti-giorti-enonoume-ta-vimata-mas-run/',
        '/agwnas/mazi-sti-giorti-enonoume-ta-vimata-mas-trail-run/',
        '/agwnas/meteora-trail-run-2025/',
        '/agwnas/olympios-dromos-2025-agonas-62chlm/',
        '/agwnas/olympus-marathon/',
        '/agwnas/opap-marathonios-lemesou-2025/',
        '/agwnas/pangytheiada-2025/',
        '/agwnas/platania-run-2025/',
        '/agwnas/poseidon-athens-half-marathon/',
        '/agwnas/poseidonia-2025/',
        '/agwnas/powerade-b2run-athens/',
        '/agwnas/pravi-trail-run/',
        '/agwnas/protochroniatikos-agonas-2025/',
        '/agwnas/rock-solid-kastellorizo-2025/',
        '/agwnas/rogkas-2025/',
        '/agwnas/run-deskati-konstantineia-2025/',
        '/agwnas/run-greece-2025-syros/',
        '/agwnas/run-greece-irakleio-2025/',
        '/agwnas/run-maroussi-spyros-louis-2025/',
        '/agwnas/skiathos-trail-run-2025/',
        '/agwnas/skyros-sports-festival-2025/',
        '/agwnas/snf-run-2025-first-run/',
        '/agwnas/sparta-city-ultra-2025/',
        '/agwnas/spetsathlon-2025/',
        '/agwnas/tihiorace-trail-running-2025/',
        '/agwnas/tihiorace-ultra-edition-2025/',
        '/agwnas/tinos-running-experience-avance-2025/',
        '/agwnas/trecho-ston-marathona-agonas-dromou-8chlm/',
        '/agwnas/triman-2025-nightrun-trifast-triswim-triman/',
        '/agwnas/tui-rhodes-marathon-2025/',
        '/agwnas/tyros-run-25-george-marneris/',
        '/agwnas/ursa-trail-2025/',
        '/agwnas/ursa-trail-2025/',
        '/agwnas/ursa-trail-2025-katara-vertical/',
        '/agwnas/vavdos-trail-run-2025/',
        '/agwnas/veikou-trail-2025/',
        '/agwnas/vertical-tsalenge/',
        '/agwnas/voio-race-series-2025-agonas-avgerinou/',
        '/agwnas/voio-race-series-2025-agonas-bourinos/',
        '/agwnas/voio-race-series-2025-agonas-namaton/',
        '/agwnas/voio-race-series-2025-agonas-neapolis/',
        '/agwnas/16os-archaios-mykinaikos-dromos/',
        '/agwnas/4o-nychterinos-agonas-rodopis/',
        '/agwnas/4o-running-palaiou-agineriou/',
        '/agwnas/patmos-chorun-2025/',
        '/agwnas/kalamata-mountain-run-2025/',
        '/agwnas/trehoume-gia-to-kdap-amea-i-paidopoli/',
        '/agwnas/5os-pallatideios-2025/',
        '/agwnas/sta-chnaria-ton-iroon-2025/',
        '/agwnas/6os-laikos-dromos-fragma-limnis-plastira-moucha-kastania/',
        '/agwnas/polylophos-run-2025/',
        '/agwnas/orestisrun-2025/',
        '/agwnas/8os-plastirios-dromos-karditsas/',
        '/agwnas/3os-dromos-thysias-kakolyri-1944/',
        '/agwnas/1o-festival-athlitismou-dytikis-manis-west-mani-sports-festival/',
        '/agwnas/6os-laikos-dromos-fragma-limnis-plastira-mouha/',
        '/agwnas/10os-crete-halfmarathon-2025/',
        '/agwnas/zagori-mountain-running-2025-challenge/',
        '/agwnas/zagori-mountain-running-2025-tera/',
        '/agwnas/zagori-mountain-running-2025-classic/',
        '/agwnas/zagori-mountain-running-2025-half-marathon/',
        '/agwnas/zagori-mountain-running-2025-forest/',
        '/agwnas/zagori-mountain-running-2025-5km-1km/',
        '/agwnas/drireia-2025/',
        '/agwnas/faethon-skyrace-2025/',
        '/agwnas/5os-krousovitis-trail-2025/',
        '/agwnas/13os-fysiolatrikos-agonas-dromou-chonous/',
        '/agwnas/13os-imimarathonios-chiou/',
        '/agwnas/17o-greece-race-for-the-cure/',
        '/agwnas/19os-agonas-dromou-13-7km-mendenitsas/',
        '/agwnas/2nd-kalamata-mountain-run/',
        '/agwnas/3o-coast-to-coast-run-keramoti-nestou/',
        '/agwnas/4o-apostolos-silas-trail-adventure/',
        '/agwnas/4o-nychterino-elafi-varybobis/',
        '/agwnas/6o-open-door-run/',
        '/agwnas/6os-agonas-parkou-nychterines-diadromes/',
        '/agwnas/6os-dromos-ygeias-almopias/',
        '/agwnas/6os-imimarathonios-kallitheas/',
        '/agwnas/6os-laikos-dromos-fragma-limnis-plastira/',
        '/agwnas/7o-naousa-vermio-trail/',
        '/agwnas/7o-syrrako-trail-run/',
        '/agwnas/7os-agonas-dromou-kalon-neron/',
        '/agwnas/8os-agonas-koufalia-hill-run/',
        '/agwnas/8os-dromos-karathonas-arvanitias/',
        '/agwnas/acheloos-run-2025/',
        '/agwnas/agones-dromou-skiadeia-2025/',
        '/agwnas/dromos-machis-marathona-2025/',
        '/agwnas/granitis-trail-running-2025/',
        '/agwnas/hercules-mountain-series-2025/',
        '/agwnas/ikaria-run-2025/',
        '/agwnas/ioannina-lake-run-2025/',
        '/agwnas/karpenos-trail-2025/',
        '/agwnas/olympia-night-run-2025/',
        '/agwnas/olympos-x-2025/',
        '/agwnas/olympus-mythical-trail-2025/',
        '/agwnas/oreinos-agonas-olympou-2025/',
        '/agwnas/poikilo-night-trail-2025/',
        '/agwnas/polygyros-run-chalkidiki-2025/',
        '/agwnas/polylofos-run-2025/',
        '/agwnas/run-greece-2025-alexandroupoli/',
        '/agwnas/run-greece-2025-peiraias/',
        '/agwnas/skloupo-trail-run-2025/',
        '/agwnas/skyros-run-2025/',
        '/agwnas/spartathlon-2025/',
        '/agwnas/sterea-run-17os-dromos-epameinonda/',
        '/agwnas/syros-trail-challenge-2025/',
        '/agwnas/triman226-2025/',
        '/agwnas/voio-race-series-2025-namata/',
      ],
    },
  },
  app: {
    head: {
      title: 'Βρες Αγώνες Δρόμου & Βουνού σε Όλη την Ελλάδα | racelist.gr',
      htmlAttrs: {
        lang: 'el',
      },
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },

        {
          rel: 'apple-touch-icon',
          sizes: '180x180',
          href: '/apple-touch-icon.png',
        },

        {
          rel: 'icon',
          type: 'image/png',
          sizes: '32x32',
          href: '/favicon-32x32.png',
        },

        {
          rel: 'icon',
          type: 'image/png',
          sizes: '16x16',
          href: '/favicon-16x16.png',
        },

        { rel: 'manifest', href: '/site.webmanifest' },

        { rel: 'canonical', href: 'https://racelist.gr' },
      ],
      meta: [
        { charset: 'utf-8' },

        { name: 'theme-color', content: '#0057A0' },

        { name: 'viewport', content: 'width=device-width, initial-scale=1.0' },

        { name: 'msvalidate.01', content: 'FA3820F660BEC14548B973CE53E161B0' },

        {
          property: 'og:title',
          content:
            'Βρες Αγώνες Δρόμου & Βουνού σε Όλη την Ελλάδα για το 2025 | racelist.gr',
        },
        {
          property: 'og:description',
          content:
            'Βρες όλους τους αγώνες δρόμου και βουνού σε κάθε γωνιά της Ελλάδας για το 2025. Ημερολόγιο με πληροφορίες και ημερομηνίες για κάθε εκδήλωση.',
        },
        { property: 'og:url', content: 'https://racelist.gr' },
        { property: 'og:type', content: 'website' },
        {
          property: 'og:image',
          content: 'https://racelist.gr/racelist-banner.jpg',
        },
        { property: 'og:site_name', content: 'racelist.gr' },
        { property: 'og:locale', content: 'el_GR' },

        { name: 'twitter:card', content: 'summary_large_image' },
        {
          name: 'twitter:title',
          content:
            'Βρες Αγώνες Δρόμου & Βουνού σε Όλη την Ελλάδα για το 2025 | racelist.gr',
        },
        {
          name: 'twitter:description',
          content:
            'Βρες όλους τους αγώνες δρόμου και βουνού σε κάθε γωνιά της Ελλάδας για το 2025. Ημερολόγιο με πληροφορίες και ημερομηνίες για κάθε εκδήλωση.',
        },
        {
          name: 'twitter:image',
          content: 'https://racelist.gr/racelist-banner.jpg',
        },

        {
          name: 'description',
          content:
            'Βρες Αγώνες Δρόμου & Βουνού σε Όλη την Ελλάδα | racelist.gr',
        },
      ],

      script: [
        {
          type: 'application/ld+json',
          innerHTML: `{
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": "racelist.gr",
            "url": "https://racelist.gr",
            "description": "Βρες όλους τους αγώνες δρόμου και βουνού σε κάθε γωνιά της Ελλάδας για το 2025. Ημερολόγιο με πληροφορίες και ημερομηνίες για κάθε εκδήλωση."
          }`,
        },
      ],
    },
  },
});
